from datetime import date
from typing import Protocol
from .domain import Task


class TaskRepository(Protocol):
    def list(self, start: date | None = None, end: date | None = None) -> list[Task]: ...
    def create(self, payload: dict) -> Task: ...
    def update(self, identifier: str, payload: dict) -> Task | None: ...
    def delete(self, identifier: str) -> bool: ...
    def set_category_color(self, category_id: str, color: str) -> None: ...
