from typing import Protocol
from .domain import Category


class CategoryRepository(Protocol):
    def list(self) -> list[Category]: ...
    def create(self, payload: dict) -> Category: ...
    def update(self, identifier: str, payload: dict) -> Category | None: ...
    def delete(self, identifier: str) -> bool: ...
    def belongs_to(self, identifier: str, user_id: str) -> bool: ...
