from typing import Protocol
from .domain import Project


class ProjectRepository(Protocol):
    def list(self) -> list[Project]: ...
    def create(self, payload: dict) -> Project: ...
    def update(self, identifier: str, payload: dict) -> Project | None: ...
    def delete(self, identifier: str) -> bool: ...
    def belongs_to(self, identifier: str, user_id: str) -> bool: ...
