from datetime import date
from typing import Protocol
from .domain import Routine, RoutineSummary, Period


class RoutineRepository(Protocol):
    def get(self, identifier: str) -> Routine | None: ...
    def create(self, payload: dict) -> Routine: ...
    def update(self, identifier: str, payload: dict) -> None: ...
    def delete(self, identifier: str) -> bool: ...
    def open_periods(self, routine_id: str) -> list[Period]: ...
    def add_period(self, routine_id: str, user_id: str, starts_on: str) -> None: ...
    def remove_period(self, identifier: str) -> None: ...
    def close_period(self, identifier: str, ends_on: str) -> None: ...
    def complete(self, routine_id: str, user_id: str, today: date, completed: bool) -> None: ...


class RoutineSummaries(Protocol):
    def summaries(self, today: date, routine_id: str | None = None) -> list[RoutineSummary]: ...
